---
settings:
  name: Astra Automation
  internal:
    pdf_enabled: true
    api_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    api_enabled: true
  rss_page: rn/whats_new.html
  versions:
  - version-number: '24.02'
    url: "/astra-automation"
  - version-number: '23.10'
    url: "/astra-automation-2310"
  - version-number: '23.07'
    url: "/astra-automation-2307"
  - version-number: '23.04'
    url: "/astra-automation-2304"
  - version-number: '22.11'
    url: "/astra-automation-2211"
  - version-number: '22.08'
    url: "/astra-automation-2208"
  - version-number: '22.04'
    url: "/astra-automation-2204"
  - version-number: '21.12'
    url: "/astra-automation-2112"
  - version-number: '21.08'
    url: "/astra-automation-2108"
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Control Automation文件
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - title: Astra REST 實作
    entries:
    - section: rest-core
    - section: endpoints
    - section: additional
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
