---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: 本網站的文件說明Astra Control REST API及Astra Control提供的相關自動化技術。 
---
= 關於本版本
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本網站的文件說明Astra Control REST API和兩種Astra部署模式最新版本隨附的相關自動化技術。

.發行步調
一般而言、Astra Control Service和Astra Control Center的更新會同時發佈。然而、Astra Control Service使用加速的發行步調、可能會在最新的Astra Control Center版本之後產生一或多個遞增更新。

由於本網站記錄兩種部署模式的REST API、因此可能包含一些僅適用於最近Astra Control Service版本的功能或變更。本網站會視需要指出兩者之間的差異。

.Astra Control部署
本網站的文件適用於Astra部署模式、如下所示。

* Astra Control Service 23.01
* Astra Control Center 22.11.


.更多資訊
請參閱下列內容、以取得有關包括REST API在內的Astra Control目前與早期版本的詳細資訊。

* link:../rn/whats_new.html["Astra Control REST API的新功能"]
* link:../endpoints/resources.html["閒置資源和端點"]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center 22.11文件"^]
* https://docs.netapp.com/us-en/astra-control-service/["Astra Control Service 23.01文件"^]
* link:../aa-earlier-versions.html["舊版Astra Automation文件"]


.參與其中
請關注我們的Twitter *@NetAppDoc*。您也可以透過成為來傳送有關文件的意見反應 link:https://docs.netapp.com/us-en/contribute/["GitHub貢獻者"^] 或傳送電子郵件至_doccomments@netapp.com_。
