---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= Astra Control REST API的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp會定期更新Astra Control REST API、為您帶來新功能、增強功能和錯誤修復。



== 2022年4月26日（22.04）

此版本包括REST API的擴充與更新、以及增強的安全性與管理功能。



=== 全新強化的Astra資源

新增兩種資源類型：*套件*和*升級*。此外、多個現有資源的版本也已升級。



=== 增強的RBAC與命名空間精細度

將角色繫結至關聯的使用者時、您可以限制使用者可存取的命名空間。請參閱*角色繫結API*參考與 link:../additional/rbac.html["RBAC安全性"] 以取得更多資訊。



=== 移除鏟斗

您可以在不再需要或無法正常運作的情況下移除貯體。



=== 支援Cloud Volumes ONTAP 功能

現在支援將其作為儲存後端。Cloud Volumes ONTAP



=== 其他產品增強功能

兩項Astra Control產品實作有多項額外增強功能、包括：

* Astra Control Center的一般入口
* 使用的私有叢集
* 支援Kubernetes 1.22
* 支援VMware Tanzu產品組合


請參閱Astra Control Center和Astra Control Service文件網站上的*新增功能*頁面。

.相關資訊
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center：最新消息"^]
* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html["Astra Control Service：最新消息"^]




== 2021年12月14日（21.12）

此版本包括擴充REST API、以及變更文件架構、以便透過未來的版本更新、更好地支援Astra Control的演進。



=== 每個Astra Control版本都有獨立的Astra Automation文件

Astra Control的每個版本都包含一個獨特的REST API、經過強化並針對特定版本的功能量身打造。Astra Control REST API每個版本的文件現在都可在專屬網站及相關的GitHub內容儲存庫中取得。主文件網站 https://docs.netapp.com/us-en/astra-automation/["Astra Control Automation"^] 永遠包含最新版本的文件。請參閱 link:../aa-earlier-versions.html["舊版Astra Control Automation文件"] 以取得先前版本的相關資訊。



=== 擴充REST資源類型

REST資源類型的數量持續增加、重點放在執行掛勾和儲存後端。新資源包括：帳戶、執行掛勾、掛機來源、執行掛勾置換、叢集節點、 託管儲存後端、命名空間、儲存設備和儲存節點。請參閱 link:../endpoints/resources.html["資源"] 以取得更多資訊。



=== NetApp Astra Control Python SDK

NetApp Astra Control Python SDK是開放原始碼套件、可讓您更輕鬆地為Astra Control環境開發自動化程式碼。核心是Astra SDK、其中包含一組類別、可抽象化REST API呼叫的複雜度。此外、還有一個工具組指令碼、可透過包裝和抽象化Python類別來執行特定的管理工作。請參閱 link:../python/astra_toolkits.html["NetApp Astra Control Python SDK"] 以取得更多資訊。



== 2021年8月5日（21.08）

此版本包括引進新的Astra部署模式、以及REST API的重大擴充。



=== Astra Control Center部署模式

除了以公有雲端服務形式提供的現有Astra Control Service產品之外、此版本也包括Astra Control Center內部部署模式。您可以在站台上安裝Astra Control Center、以管理本機Kubernetes環境。這兩種Astra Control部署模式共用相同的REST API、但文件中所指出的細微差異較小。



=== 擴充REST資源類型

透過Astra Control REST API存取的資源數量已大幅增加、許多新資源為內部部署的Astra Control Center產品提供了基礎。新資源包括：ASUP、權利、功能、授權、設定、 訂購、儲存庫、雲端、叢集、託管叢集、 儲存後端與儲存類別。請參閱 link:../endpoints/resources.html["資源"] 以取得更多資訊。



=== 支援Astra部署的其他端點

除了擴充的REST資源之外、還有其他幾個新的API端點可供支援Astra Control部署。

OpenAPI支援:: OpenAPI端點可讓您存取目前的OpenAPI Json文件及其他相關資源。
OpenMetrics支援:: OpenMetrics端點可透過OpenMetrics資源存取帳戶指標。




== 2021年4月15日（21.04）

此版本包含下列新功能與增強功能。



=== 介紹REST API

Astra Control REST API可搭配Astra Control Service產品使用。這是以REST技術和目前最佳實務做法為基礎所建立。API為Astra部署的自動化提供基礎、並提供下列功能與優勢。

資源:: 共有14種REST資源類型可供使用。
API權杖存取:: 您可透過Astra網路使用者介面產生的API存取權杖來存取REST API。API權杖可提供對API的安全存取。
支援集合:: 有一組豐富的查詢參數可用來存取資源集合。部分支援的作業包括篩選、排序及分頁。

