---
sidebar: sidebar 
permalink: workflows_infra/wf_create_user.html 
keywords:  
summary: 您可以建立具有特定認證和預先定義角色的使用者。您也可以選擇性地限制使用者對特定命名空間的存取。 
---
= 建立使用者
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以建立具有特定認證和預先定義角色的使用者。您也可以選擇性地限制使用者對特定命名空間的存取。



=== 1.選取使用者名稱

執行工作流程 link:../workflows_infra/wf_list_users.html["列出使用者"] 並選取目前未使用的可用名稱。



=== 2.建立使用者

執行下列REST API呼叫以建立使用者。成功完成通話之後、新使用者將無法使用。

[cols="25,75"]
|===
| HTTP方法 | 路徑 


| 貼文 | /Accounts /｛account_id｝/核心/ v1 /使用者 
|===


===== JSONN輸入範例

[source, curl]
----
{
  "type" :  "application/astra-user",
  "version" : "1.1",
  "firstName" : "John",
  "lastName" : "West",
  "email" : "jwest@example.com"
}
----


===== Curl範例

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/users' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----


===== Json輸出範例

[source, curl]
----
{
    "metadata": {
        "creationTimestamp": "2022-11-20T17:23:15Z",
        "modificationTimestamp": "2022-11-20T17:23:15Z",
        "createdBy": "a20e91f3-2c49-443b-b240-615d940ec5f3",
        "labels": []
    },
    "type": "application/astra-user",
    "version": "1.2",
    "id": "d07dac0a-a328-4840-a216-12de16bbd484",
    "authProvider": "local",
    "authID": "jwest@example.com",
    "firstName": "John",
    "lastName": "West",
    "companyName": "",
    "email": "jwest@example.com",
    "postalAddress": {
        "addressCountry": "",
        "addressLocality": "",
        "addressRegion": "",
        "streetAddress1": "",
        "streetAddress2": "",
        "postalCode": ""
    },
    "state": "active",
    "sendWelcomeEmail": "false",
    "isEnabled": "true",
    "isInviteAccepted": "true",
    "enableTimestamp": "2022-11-20T17:23:15Z",
    "lastActTimestamp": ""
}
----


=== 3.選擇性選取允許的命名空間

執行工作流程 link:../workflows/wf_list_namespaces.html["列出命名空間"] 然後選取您要限制存取的命名空間。



=== 4.將使用者繫結至角色

執行下列REST API呼叫、將使用者繫結至角色。以下範例對命名空間存取沒有任何限制。請參閱 link:../additional/rbac.html#enhanced-rbac-with-namespace-granularity["增強的RBAC與命名空間精細度"] 以取得更多資訊。

[cols="25,75"]
|===
| HTTP方法 | 路徑 


| 貼文 | /Accounts /｛account_id｝/核心/ v1/roleBindings 
|===


===== JSONN輸入範例

[source, curl]
----
{
  "type" :  "application/astra-roleBinding",
  "version" : "1.1",
  "userID" : "d07dac0a-a328-4840-a216-12de16bbd484",
  "accountID" : "29e1f39f-2bf4-44ba-a191-5b84ef414c95",
  "role" : "viewer",
  "roleConstraints": [ "*" ]
}
----


===== Curl範例

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/roleBindings' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----


=== 5.建立認證資料

執行下列REST API呼叫、以建立認證並將其與使用者建立關聯。此範例使用以base64值提供的密碼。。 `name` 內容應包含上一步傳回的使用者ID。輸入內容 `change` 也必須以base64編碼、並決定使用者是否必須在第一次登入時變更密碼 (`true` 或 `false`）。


NOTE: 此步驟僅適用於使用本機驗證的Astra Control Center部署。使用LDAP或Astra Control Service部署的Astra Control Center不需要此功能。

[cols="25,75"]
|===
| HTTP方法 | 路徑 


| 貼文 | /Accounts /｛account_id｝/核心/ v1 /認證 
|===


===== JSONN輸入範例

[source, curl]
----
{
  "type" :  "application/astra-credential",
  "version" : "1.1",
  "name" : "d07dac0a-a328-4840-a216-12de16bbd484",
  "keyType" : "passwordHash",
  "keyStore" : {
      "cleartext" : "TmV0QXBwMTIz",
      "change" : "ZmFsc2U="
  },
  "valid" : "true"
}
----


===== Curl範例

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/credentials' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----