---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= 列出未受管理的應用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以列出目前未由Astra管理的應用程式。您可以在選擇要管理的應用程式時執行此動作。


NOTE: 依預設、這些工作流程中使用的REST端點會傳回所有Astra應用程式。您可以在API呼叫上使用「filter」查詢參數、只要求傳回未受管理的應用程式。您也可以省略filter參數來傳回所有應用程式、然後檢查輸出中的「managedState」欄位、以判斷哪些應用程式處於「Unmanaged」狀態。



== 僅列出管理狀態等於Unmanaged的應用程式

此工作流程使用「filter」查詢參數、只傳回未受管理的應用程式。



=== 1.列出未受管理的應用程式

執行下列REST API呼叫。

[cols="25,75"]
|===
| HTTP方法 | 路徑 


| 取得 | /Account/{AccountID}/topology / v1/apps 
|===


===== 其他輸入參數

除了所有REST API呼叫通用的參數之外、此步驟的Curl範例也會使用下列參數。

[cols="25,10,10,55"]
|===
| 參數 | 類型 | 必要 | 說明 


| 篩選器 | 查詢 | 否 | 使用篩選器來指定應傳回哪些應用程式。 


| 包括 | 查詢 | 否 | 選擇性地選取您要傳回回應中的值。 
|===


===== Curl範例：傳回未受管理應用程式的名稱、ID和管理狀態

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?filter=managedState%20eq%20'unmanaged'&include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Json輸出範例

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ]
  ],
  "metadata": {}
}
----


== 列出所有應用程式、然後選取未受管理的應用程式

此工作流程會傳回所有應用程式。您必須檢查輸出、判斷哪些是未受管理的。



=== 1.列出所有應用程式

執行下列REST API呼叫。

[cols="25,75"]
|===
| HTTP方法 | 路徑 


| 取得 | /Account/{AccountID}/topology / v1/apps 
|===


===== 其他輸入參數

除了所有REST API呼叫通用的參數之外、此步驟的Curl範例也會使用下列參數。

[cols="25,10,10,55"]
|===
| 參數 | 類型 | 必要 | 說明 


| 包括 | 查詢 | 否 | 選擇性地選取您要傳回回應中的值。 
|===


===== Curl範例：傳回所有應用程式的所有資料

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl範例：傳回所有應用程式的名稱、ID和管理狀態

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Json輸出範例

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----


=== 2.選取未受管理的應用程式

檢閱API呼叫的輸出、然後手動選取「managedState」等於「Unmanaged」的應用程式。
