---
sidebar: sidebar 
permalink: workflows/workflows_before.html 
keywords:  
summary:  
---
= 開始之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用這些工作流程來管理Astra託管叢集內的應用程式。


NOTE: NetApp可隨時擴充及強化這些工作流程、因此您應定期檢閱。



== 一般準備

使用任何Astra工作流程之前、請務必先檢閱 link:../get-started/prepare_to_use_workflows.html["準備好使用工作流程"]。



== 工作流程類別

管理工作流程會依不同類別進行組織、以便更容易找到您想要的工作流程。

[cols="25,75"]
|===
| 類別 | 說明 


| 應用程式控制 | 這些工作流程可讓您控制託管及未受管理的應用程式。您可以列出應用程式、以及建立和移除託管應用程式。 


| 應用程式保護 | 您可以使用這些工作流程、透過快照和備份來保護託管應用程式。 


| 複製及還原應用程式 | 這些工作流程說明如何複製及還原託管應用程式。 


| 支援 | 有幾種工作流程可用來偵錯及支援您的應用程式、以及一般Kubernetes環境。 
|===


== 其他考量

使用管理工作流程時、還有幾項額外考量。



=== 複製應用程式

複製應用程式時、需要考量一些事項。下列參數是Json輸入的一部分。

來源叢集識別碼:: 「資源叢集ID」的值一律會識別安裝原始應用程式的叢集。
叢集識別碼:: 「clusterid」的值表示要安裝新應用程式的叢集。
+
--
* 在同一個叢集內進行複製時、「clusterid」和「資源叢集ID」的值相同。
* 在叢集之間進行複製時、兩個值不同、而「clusterid」應為目標叢集的ID。


--
命名空間:: 「命名空間」值必須與原始來源應用程式不同。此外、複本的命名空間也不存在、Astra也會建立該名稱空間。
備份與快照:: 您可以選擇使用「backupID」或「snapshotID」參數、從現有的備份或快照複製應用程式。如果您未提供備份或快照、Astra會先建立應用程式的備份、然後從備份複製。




==== 還原應用程式

以下是還原應用程式時的幾項考量事項。

* 還原應用程式與複製作業非常類似。
* 還原應用程式時、您必須提供備份或快照。

